---
title: "Modeling Response Time: The F > C Phenomenon and the Distance-Difficulty Hypothesis"
author:
  - name: Nicole Bonge
    orcid: 0009-0003-0609-6576
    corresponding: true
    email: ngbonge@uark.edu
    affiliations:
      - University of Arkansas
  - name: Ronna C. Turner
    orcid: 0000-0002-2984-7649
    corresponding: false
    affiliations:
      - University of Arkansas
keywords:
  - Response Time
  - Item Response Theory
  - Multilevel Modeling
abstract: |
 Response time has long been thought to be closely related with intelligence via processing speed. If asked to describe a genius, one might describe a person who can do complex mental calculations quickly and with ease. This stereotype that students with high ability level tend to answer questions fastest has come under question, however, with research indicating that response time is a complex process, dependent on more than just ability level. In this study, we use multilevel linear models to analyze the responses and response times on the 2019 TIMSS mathematics achievement test for eighth-grade students in the United States. Our results demonstrate response time’s dependency on student ability level, whether the student answered the item correctly (F > C phenomenon), and item difficulty in relation to the student’s ability level (distance-difficulty hypothesis). We find evidence to support the F > C phenomenon, the distance-difficulty hypothesis, and an interaction between the two. Our results affirm the complexity of cognitive processes involved in item responses, and challenge the widespread use of response time as a stand-alone metric to assess item quality and respondent effort.  
date: 04/25/2025
published-title: "Presentation Date"
bibliography: references.bib
number-sections: true
---

## Introduction
Researchers have long contemplated the role of response time in achievement testing, and how time-to-completion can inform about an item functioning and participant performance. Among researchers, it is a widely held belief that response time is indicative of the cognitive effort required to answer an item (Höhne et al., 2007), so researchers use response time to gauge item quality and comprehensibility (Bassili et al., 1996; Lenzner, 2012; Lenzner et al., 2010), to detect respondent fatigue (Nguyen, 2017), effort (Bowling et al., 2023; Krosnick, 1991; Ulitzsch et al., 2022), and other characteristics such as persistence, motivation, and disengagement (e.g., Nagy & Ulitzsch, 2021; Wise & Demars, 2006). Researchers have also used response time to investigate other cognitive processes underlying item responses (De Boeck & Jeon, 2019), with recent research challenging the long-held “faster equals smarter” stereotype (Gernsbacher et al., 2020).  

In this study, we extend previous models posed by Tancoš et al. (2023) to achievement data, arguing that response time depends on (1) item difficulty, (2) respondent ability level, (3) the distance between the item’s difficulty and the respondent’s ability level (referred to as the distance-difficulty hypothesis; Thissen, 1983), and (4) whether the respondent answered the item correctly (F > C phenomenon; Beckmann, 2000).  

## Theoretical Framework
### The F > C Phenomenon
One approach to modelling response time is the F > C (False > Correct) phenomenon (Beckmann, 2000), also called the I > C phenomenon, which posits that respondents take longer to report incorrect answers than they take to provide correct ones. Formally, the F > C phenomenon is given by (Beckmann, 2000, as cited in Tancoš et al., 2023, p. 3):
$$t_{ij} = \mu + \gamma FC_{ij} + \epsilon_{ij},$$ {#eq-FC}
where $t_{ij}$ is the response time of respondent $j$ on item $i$; $\mu$ is an intercept representing the average response time across all items and respondents; $FC_{ij}$ is a binary indicator representing whether respondent $j$ answered item $i$ correctly; $\gamma$ is an unstandardized regression coefficient representin the mean difference 

## Data & Methods {#sec-data-methods}

## Conclusion

## References {.unnumbered}

:::{#refs}

:::